name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # Replace 'your-repo-name' with your actual repository name
        run: flutter build web --release --base-href "/cv-chatbot/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
